Revert "Fix: kernel/arch/arm/include/asm/setup.h:18:27: fatal error: mach/dfo_boot.h: No such file or directoryignore mach/dfo_boot.h"
This reverts commit 062d7cbbedb969b6675acb73c6ff9aefe97ac3e7.